{
 "title": "App",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(zio_microservice_request_total{job=\"zio-microservice\"}[$__range])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Health checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(zio_microservice_request_total{path=\"/health\"}[$__range])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(zio_microservice_request_total{status!=\"2xx\"}[$__range])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(path) (increase(zio_microservice_request_total[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path) (histogram_quantile(0.9, sum_over_time(zio_microservice_request_duration_seconds_bucket[$__interval])))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by(path) (increase(zio_microservice_request_total{status!=\"2xx\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "External requests stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(zio_microservice_total_external_requests[$__range])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Gauge",
   "type": "gauge",
   "description": "Percentage of errors per requests",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(zio_microservice_total_external_requests{status!=\"2xx\"}[$__range]))/sum(increase(zio_microservice_total_external_requests[$__range]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(zio_microservice_total_external_requests{status!=\"2xx\"}[$__range])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(service) (increase(zio_microservice_total_external_requests[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by(service, url) (increase(zio_microservice_total_external_requests{status!=\"2xx\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "JVM stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "ZIO Fiber Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "zio_fiber_started", "legendFormat": "Fibers started" },
    { "expr": "zio_fiber_successes", "legendFormat": "Fibers succeeded" }
   ]
  },
  {
   "title": "JVM memory bytes used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "JVM Current Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "ZIO fiber fork locations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zio_fiber_fork_locations", "legendFormat": "{{bucket}}" }
   ]
  }
 ]
}