name: Publish Library

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Library version'
        type: string
        required: true
      repository:
        description: 'Repository'
        required: true
        default: 'private'
        type: choice
        options:
          - releases
          - private
          - snapshots

permissions:
  contents: read
  packages: write

jobs:
  publish_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Library
        env:
          VERSION: ${{inputs.version}}
          REPOSITORY: ${{inputs.repository}}
          ARTIFACT_TOKEN: ${{secrets.ARTIFACT_TOKEN}}
          DEV_ID: ${{secrets.DEV_ID}}
        run: sbt core/publish