name: Scala CI

on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
    branches:
      - master
      - develop
      - main

env:
  ARTIFACT_TOKEN: ${{secrets.ARTIFACT_TOKEN}}
  DEV_ID: ${{secrets.DEV_ID}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Run tests
        run: sbt clean test
#      - name: Coverage Report
#        run: sbt coverageReport
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Formatting
        run: sbt clean scalafmtSbtCheck scalafmtCheck test:scalafmtCheck